// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjin96w8zKTUATYWftmRxhjOodUiCEBEU',
    appId: '1:120765921327:web:6e1ebeda885d8b97586eda',
    messagingSenderId: '120765921327',
    projectId: 'smartlifepersonal-3a8c2',
    authDomain: 'smartlifepersonal-3a8c2.firebaseapp.com',
    storageBucket: 'smartlifepersonal-3a8c2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDujG-wWI7Bc7ZHjsEoHr6Y1WlSabFChbw',
    appId: '1:120765921327:android:704e9d83a5a9b6af586eda',
    messagingSenderId: '120765921327',
    projectId: 'smartlifepersonal-3a8c2',
    storageBucket: 'smartlifepersonal-3a8c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6RSznpvujzulR_Hv-NKWWZ0niaj3kVD4',
    appId: '1:120765921327:ios:33813c5c154d93c6586eda',
    messagingSenderId: '120765921327',
    projectId: 'smartlifepersonal-3a8c2',
    storageBucket: 'smartlifepersonal-3a8c2.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6RSznpvujzulR_Hv-NKWWZ0niaj3kVD4',
    appId: '1:120765921327:ios:33813c5c154d93c6586eda',
    messagingSenderId: '120765921327',
    projectId: 'smartlifepersonal-3a8c2',
    storageBucket: 'smartlifepersonal-3a8c2.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjin96w8zKTUATYWftmRxhjOodUiCEBEU',
    appId: '1:120765921327:web:a9862f8b2dbf1dd8586eda',
    messagingSenderId: '120765921327',
    projectId: 'smartlifepersonal-3a8c2',
    authDomain: 'smartlifepersonal-3a8c2.firebaseapp.com',
    storageBucket: 'smartlifepersonal-3a8c2.firebasestorage.app',
  );
}
